### ISSUE TITLE
Snap installation of prjxray missing import

### ISSUE THREAD

**Issue by maij** [openXC7/toolchain-installer#3] opened 2023-12-24 00:19 UTC
Just installed this toolchain via the snap installer (Ubuntu 22.04.03) and it seems to have failed to set up prjxray in the snap.
I've tried this for the demo projects and the same problem appears in each.

```
Info: Running post-routing legalisation...
fasm2frames --part xc7a35tcsg324-1 --db-root /snap/openxc7/current/opt/nextpnr-xilinx/external/prjxray-db/artix7 blinky.fasm > blinky.frames
Traceback (most recent call last):
  File "/usr/local/bin/fasm2frames", line 33, in <module>
    sys.exit(load_entry_point('prjxray', 'console_scripts', 'fasm2frames')())
  File "/usr/local/bin/fasm2frames", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for prjxray
make: *** [../openXC7.mk:43: blinky.frames] Error 1
```

**Comment by hansfbaier** [comment] 2023-12-26 05:03
Works for me here, running the same Ubuntu :\
```
[12:00:59] ~ $ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
[12:01:04] ~ $ fasm2frames
/snap/openxc7/current/usr/lib/python3/dist-packages/fasm/parser/__init__.py:30: RuntimeWarning: Unable to import fast Antlr4 parser implementation.
  ImportError: cannot import name 'antlr_to_tuple' from partially initialized module 'fasm.parser' (most likely due to a circular import) (/snap/openxc7/current/usr/lib/python3/dist-packages/fasm/parser/__init__.py)

  Falling back to the much slower pure Python textX based parser
  implementation.

  Getting the faster antlr parser can normally be done by installing the
  required dependencies and then reinstalling the fasm package with:
    pip uninstall
    pip install -v fasm

  warn(
usage: fasm2frames [-h] --db-root DB_ROOT --part PART [--sparse] [--roi ROI] [--emit_pudc_b_pullup] [--debug] fn_in [fn_out]
fasm2frames: error: the following arguments are required: --db-root, --part, fn_in
[12:01:07] ~ $ snap info openxc7
name:      openxc7
summary:   yosys/nextpnr-xilinx based PnR FPGA toolchain for Xilinx 7 series FPGAs
publisher: –
license:   unset
description: |
  Pre-packaged toolchain nextpnx-xilinx with support for Xilinx 7 series FPGAs
  (Spartan7, Artix7, Kintex7, Zynq7)
  Includes support for Kintex FPGAs
  This package does not include Yosys, which needs to be installed separately.
commands:
  - openxc7.bbasm
  - openxc7.bit2fasm
  - openxc7.fasm
  - openxc7.fasm2frames
  - openxc7.nextpnr-xilinx
  - openxc7.xc7frames2bit
refresh-date: 11 days ago, at 12:08 WIB
installed:    0.7.0 (x1) 168MB classic
[12:01:22] ~ $
```

I would really recommend the nix toolchain, because it is more up to date (I push bug fixes immediately)
and because nix has been explicitly designed to fix the 'works on my machine' syndrome.
You can also use the containerized version of that one:
https://github.com/openXC7/toolchain-nix/

**Comment by hansfbaier** [comment] 2023-12-26 05:04
Sorry to close this, because I cannot reproduce.

**Closed as completed by hansfbaier** 2023-12-26 05:04 UTC

**Comment by maij** [comment] 2023-12-26 10:15
Thanks for looking into this, I just found out that the fasm2frames alias to openxc7.fasm2frames wasn't being created during install because I had an old fasm2frames from prjxray. I removed those binaries, uninstalled and reinstalled the snap package to verify it works and it does. I can successfully run the full flow now. 

Thanks for your help, and making this simple toolchain!

**Comment by hansfbaier** [comment] 2023-12-26 10:21
That is good to hear. Thanks!
